name: Build and test

on:
  push:
    branches:
      - '*'
    paths:
      - 'src/**'
      - 'test/**'
      - 'project.clj'
      - 'deps.edn'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Choose Java 11
        run: |
          echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV
          echo "$JAVA_HOME_11_X64/bin" >> $GITHUB_PATH
      - run: ./script/test_clj.sh
      - run: ./script/test_cljs.sh
      - run: ./script/test_js.sh
